[build]
  command = "npm run build --legacy-peer-deps"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200                                                                                  
